apiVersion: apps/v1
kind: Deployment
metadata:
  name: color
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/w4hf/k8s-samples/tree/main/color-app'
  labels:
    app: color
    app.kubernetes.io/name: color
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: color
    app.openshift.io/runtime: python
    app.kubernetes.io/part-of: color
spec:
  selector:
    matchLabels:
      name: color
  replicas: 1
  template:
    metadata:
      labels:
        name: color
    spec:
      containers:
        - name: color
          image: quay.io/hbouabda/color-app:v1
          imagePullPolicy: Always
          env:
            - name: APP_BG_COLOR
              value: red
          ports:
          - containerPort: 5000
            protocol: TCP
            name: http
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
