apiVersion: apps/v1
kind: Deployment
metadata:
  name: doks-example
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doks-example
  template:
    metadata:
      labels:
        app: doks-example
    spec:
      containers:
      - name: nginx
        image: digitalocean/doks-example
        ports:
        - containerPort: 80
          protocol: TCP
