kind: Service
apiVersion: v1
metadata:
  name: doks-example
  namespace: test
spec:
  selector:
    app: doks-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
